#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : project_design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Fri Jan 08 01:13:57 +0300 2021
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: project_design_1.sh [-help]
# usage: project_design_1.sh [-lib_map_path]
# usage: project_design_1.sh [-noclean_files]
# usage: project_design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'project_design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "project_design_1.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/project_design_1/ipshared/37a5/src/xup_dff_en_reset.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_0/sim/project_design_1_xup_dff_en_reset_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_1/sim/project_design_1_xup_dff_en_reset_0_1.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_2/sim/project_design_1_xup_dff_en_reset_0_2.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_3/sim/project_design_1_xup_dff_en_reset_0_3.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_4/sim/project_design_1_xup_dff_en_reset_0_4.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_5/sim/project_design_1_xup_dff_en_reset_0_5.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_6/sim/project_design_1_xup_dff_en_reset_0_6.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_7/sim/project_design_1_xup_dff_en_reset_0_7.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_8/sim/project_design_1_xup_dff_en_reset_0_8.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_9/sim/project_design_1_xup_dff_en_reset_0_9.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_10/sim/project_design_1_xup_dff_en_reset_0_10.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_11/sim/project_design_1_xup_dff_en_reset_0_11.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_12/sim/project_design_1_xup_dff_en_reset_0_12.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_13/sim/project_design_1_xup_dff_en_reset_0_13.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_14/sim/project_design_1_xup_dff_en_reset_0_14.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_dff_en_reset_0_15/sim/project_design_1_xup_dff_en_reset_0_15.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/0118/src/xup_or3.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or3_0_0/sim/project_design_1_xup_or3_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/8053/src/xup_or4.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or4_0_0/sim/project_design_1_xup_or4_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/2167/src/xup_and3.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and3_0_0/sim/project_design_1_xup_and3_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/9859/src/xup_and2.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_0_0/sim/project_design_1_xup_and2_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/c3d7/src/xup_or2.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_0_0/sim/project_design_1_xup_or2_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/67eb/src/xup_inv.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_1_0/sim/project_design_1_xup_inv_1_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_1_0/sim/project_design_1_xup_and2_1_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_1_0/sim/project_design_1_xup_or2_1_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_2_0/sim/project_design_1_xup_and2_2_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or3_1_0/sim/project_design_1_xup_or3_1_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_3_0/sim/project_design_1_xup_and2_3_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or3_2_0/sim/project_design_1_xup_or3_2_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_4_0/sim/project_design_1_xup_and2_4_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_5_0/sim/project_design_1_xup_and2_5_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_2_0/sim/project_design_1_xup_or2_2_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_3_0/sim/project_design_1_xup_or2_3_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_2_0/sim/project_design_1_xup_inv_2_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_3_0/sim/project_design_1_xup_inv_3_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/6be6/src/xup_and5.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and5_0_0/sim/project_design_1_xup_and5_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_4_0/sim/project_design_1_xup_or2_4_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_4_0/sim/project_design_1_xup_inv_4_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_5_0/sim/project_design_1_xup_or2_5_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_6_0/sim/project_design_1_xup_and2_6_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_6_0/sim/project_design_1_xup_or2_6_0.v" \
    "$ref_dir/../../../bd/project_design_1/ipshared/8301/src/xup_and4.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and4_0_0/sim/project_design_1_xup_and4_0_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or4_1_0/sim/project_design_1_xup_or4_1_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_5_0/sim/project_design_1_xup_inv_5_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_6_0/sim/project_design_1_xup_inv_6_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_7_0/sim/project_design_1_xup_or2_7_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or2_8_0/sim/project_design_1_xup_or2_8_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or4_2_0/sim/project_design_1_xup_or4_2_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or4_3_0/sim/project_design_1_xup_or4_3_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or4_4_0/sim/project_design_1_xup_or4_4_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or3_3_0/sim/project_design_1_xup_or3_3_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_or3_4_0/sim/project_design_1_xup_or3_4_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/project_design_1/sim/project_design_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_0_1/sim/project_design_1_xup_inv_0_1.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_8_0/sim/project_design_1_xup_and2_8_0.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_and2_7_1/sim/project_design_1_xup_and2_7_1.v" \
    "$ref_dir/../../../bd/project_design_1/ip/project_design_1_xup_inv_7_0/sim/project_design_1_xup_inv_7_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.project_design_1 xil_defaultlib.glbl -o project_design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./project_design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./project_design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key project_design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc project_design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./project_design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: project_design_1.sh [-help]\n\
Usage: project_design_1.sh [-lib_map_path]\n\
Usage: project_design_1.sh [-reset_run]\n\
Usage: project_design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
