# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/design_2_design_1_wrapper_0_1.xci
# IP: The module: 'design_2_design_1_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_5/design_1_xup_and2_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_5 || ORIG_REF_NAME==design_1_xup_and2_0_5} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_1/design_1_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_1 || ORIG_REF_NAME==design_1_xup_and2_0_1} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_3/design_1_xup_and2_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_3 || ORIG_REF_NAME==design_1_xup_and2_0_3} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_4/design_1_xup_and2_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_4 || ORIG_REF_NAME==design_1_xup_and2_0_4} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_6/design_1_xup_and2_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_6 || ORIG_REF_NAME==design_1_xup_and2_0_6} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_7/design_1_xup_and2_0_7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_7 || ORIG_REF_NAME==design_1_xup_and2_0_7} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_inv_0_1/design_1_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_1 || ORIG_REF_NAME==design_1_xup_inv_0_1} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_2/design_1_xup_and2_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_2 || ORIG_REF_NAME==design_1_xup_and2_0_2} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/design_1_ooc.xdc

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/design_2_design_1_wrapper_0_1.xci
# IP: The module: 'design_2_design_1_wrapper_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_5/design_1_xup_and2_0_5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_5 || ORIG_REF_NAME==design_1_xup_and2_0_5} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_inv_0_0/design_1_xup_inv_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_0 || ORIG_REF_NAME==design_1_xup_inv_0_0} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_1/design_1_xup_and2_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_1 || ORIG_REF_NAME==design_1_xup_and2_0_1} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_3/design_1_xup_and2_0_3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_3 || ORIG_REF_NAME==design_1_xup_and2_0_3} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_4/design_1_xup_and2_0_4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_4 || ORIG_REF_NAME==design_1_xup_and2_0_4} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_6/design_1_xup_and2_0_6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_6 || ORIG_REF_NAME==design_1_xup_and2_0_6} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_7/design_1_xup_and2_0_7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_7 || ORIG_REF_NAME==design_1_xup_and2_0_7} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_inv_0_1/design_1_xup_inv_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_inv_0_1 || ORIG_REF_NAME==design_1_xup_inv_0_1} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_2/design_1_xup_and2_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_2 || ORIG_REF_NAME==design_1_xup_and2_0_2} -quiet] -quiet

# IP: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/ip/design_1_xup_and2_0_0/design_1_xup_and2_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_xup_and2_0_0 || ORIG_REF_NAME==design_1_xup_and2_0_0} -quiet] -quiet

# XDC: c:/Users/E.D/AppData/Roaming/Xilinx/Vivado/lab_project_5_b/lab_project_5_b.srcs/sources_1/bd/design_2/ip/design_2_design_1_wrapper_0_1/sources_1/bd/design_1/design_1_ooc.xdc
