# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_6_1/design_6_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_6_1 || ORIG_REF_NAME==design_6_1} -quiet] -quiet

# IP: bd/design_6_1/ip/design_6_1_xup_or2_0_0/design_6_1_xup_or2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_6_1_xup_or2_0_0 || ORIG_REF_NAME==design_6_1_xup_or2_0_0} -quiet] -quiet

# IP: bd/design_6_1/ip/design_6_1_xup_or2_0_1/design_6_1_xup_or2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_6_1_xup_or2_0_1 || ORIG_REF_NAME==design_6_1_xup_or2_0_1} -quiet] -quiet

# IP: bd/design_6_1/ip/design_6_1_xup_or4_0_0/design_6_1_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_6_1_xup_or4_0_0 || ORIG_REF_NAME==design_6_1_xup_or4_0_0} -quiet] -quiet

# IP: bd/design_6_1/ip/design_6_1_xup_and2_0_0/design_6_1_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_6_1_xup_and2_0_0 || ORIG_REF_NAME==design_6_1_xup_and2_0_0} -quiet] -quiet

# IP: bd/design_6_1/ip/design_6_1_xup_inv_0_0/design_6_1_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_6_1_xup_inv_0_0 || ORIG_REF_NAME==design_6_1_xup_inv_0_0} -quiet] -quiet

# XDC: bd/design_6_1/design_6_1_ooc.xdc
