# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_lab_8/design_lab_8.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8 || ORIG_REF_NAME==design_lab_8} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_dff_en_reset_0_0/design_lab_8_xup_dff_en_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_dff_en_reset_0_0 || ORIG_REF_NAME==design_lab_8_xup_dff_en_reset_0_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_dff_en_reset_0_1/design_lab_8_xup_dff_en_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_dff_en_reset_0_1 || ORIG_REF_NAME==design_lab_8_xup_dff_en_reset_0_1} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_dff_en_reset_0_2/design_lab_8_xup_dff_en_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_dff_en_reset_0_2 || ORIG_REF_NAME==design_lab_8_xup_dff_en_reset_0_2} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_inv_0_0/design_lab_8_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_inv_0_0 || ORIG_REF_NAME==design_lab_8_xup_inv_0_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_inv_0_1/design_lab_8_xup_inv_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_inv_0_1 || ORIG_REF_NAME==design_lab_8_xup_inv_0_1} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_inv_0_2/design_lab_8_xup_inv_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_inv_0_2 || ORIG_REF_NAME==design_lab_8_xup_inv_0_2} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_inv_0_3/design_lab_8_xup_inv_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_inv_0_3 || ORIG_REF_NAME==design_lab_8_xup_inv_0_3} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and4_0_0/design_lab_8_xup_and4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and4_0_0 || ORIG_REF_NAME==design_lab_8_xup_and4_0_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and2_0_0/design_lab_8_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and2_0_0 || ORIG_REF_NAME==design_lab_8_xup_and2_0_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and2_0_1/design_lab_8_xup_and2_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and2_0_1 || ORIG_REF_NAME==design_lab_8_xup_and2_0_1} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_or3_0_0/design_lab_8_xup_or3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_or3_0_0 || ORIG_REF_NAME==design_lab_8_xup_or3_0_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and2_1_0/design_lab_8_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and2_1_0 || ORIG_REF_NAME==design_lab_8_xup_and2_1_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and2_3_0/design_lab_8_xup_and2_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and2_3_0 || ORIG_REF_NAME==design_lab_8_xup_and2_3_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and2_4_0/design_lab_8_xup_and2_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and2_4_0 || ORIG_REF_NAME==design_lab_8_xup_and2_4_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_or4_0_0/design_lab_8_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_or4_0_0 || ORIG_REF_NAME==design_lab_8_xup_or4_0_0} -quiet] -quiet

# IP: bd/design_lab_8/ip/design_lab_8_xup_and2_5_0/design_lab_8_xup_and2_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_lab_8_xup_and2_5_0 || ORIG_REF_NAME==design_lab_8_xup_and2_5_0} -quiet] -quiet

# XDC: bd/design_lab_8/design_lab_8_ooc.xdc
