# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/prime_design/prime_design.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design || ORIG_REF_NAME==prime_design} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_and2_0_0/prime_design_xup_and2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_and2_0_0 || ORIG_REF_NAME==prime_design_xup_and2_0_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_and2_1_0/prime_design_xup_and2_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_and2_1_0 || ORIG_REF_NAME==prime_design_xup_and2_1_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_and2_2_0/prime_design_xup_and2_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_and2_2_0 || ORIG_REF_NAME==prime_design_xup_and2_2_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_and3_0_0/prime_design_xup_and3_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_and3_0_0 || ORIG_REF_NAME==prime_design_xup_and3_0_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_inv_0_0/prime_design_xup_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_inv_0_0 || ORIG_REF_NAME==prime_design_xup_inv_0_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_inv_1_0/prime_design_xup_inv_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_inv_1_0 || ORIG_REF_NAME==prime_design_xup_inv_1_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_inv_2_0/prime_design_xup_inv_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_inv_2_0 || ORIG_REF_NAME==prime_design_xup_inv_2_0} -quiet] -quiet

# IP: bd/prime_design/ip/prime_design_xup_or4_0_0/prime_design_xup_or4_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prime_design_xup_or4_0_0 || ORIG_REF_NAME==prime_design_xup_or4_0_0} -quiet] -quiet

# XDC: bd/prime_design/prime_design_ooc.xdc
